### ISSUE TITLE
ubutuon18.04 build Error

### ISSUE THREAD

**Issue by moondaiy** [smistad/FAST#114]
Hi Thans to your work ,but i encounter en error when i build the project

ERROR: Feature 'opengl-desktop' was enabled, but the pre-condition '(config.win32 && !config.winrt && !features.opengles2 && (config.msvc || libs.opengl))
                          || (!config.watchos && !config.win32 && libs.opengl)' failed.

ERROR: The OpenGL functionality tests failed!
You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2],
QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.

**Comment by smistad** [comment]
Hi, have you installed OpenGL/graphics driver on your system? You can check so using the command "glxinfo"

**Comment by moondaiy** [comment]
> Hi, have you installed OpenGL/graphics driver on your system? You can check so using the command "glxinfo"

Hi Thans for you reply
I have install OpenGL and OpenCL and CUDA on my pc

I write OpenCL and OpenGL projection and success run on my PC

By the way cmake give warning as below

-- Configuring done
CMake Warning (dev) at CMake/OpenIGTLinkCMakeTests.cmake:8 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "OpenIGTLink_HAVE_GETSOCKNAME_WITH_SOCKLEN_T" will no
  longer be dereferenced when the policy is set to NEW.  Since the policy is
  not set the OLD behavior will be used.

**Comment by smistad** [comment]
From the error message it seems that Qt is unable find OpenGL. But you clearly have OpenGL installed, so the issue must be that Qt is not able to find OpenGL because it installed in a non-standard place. You could try: 
1) install mesa GL dev package (sudo apt install libgl1-mesa-dev), 
2) reinstalling the nvidia driver, 
3) adding the path to your libGL.so to LD_LIBRARY_PATH (export LD_LIBRARY_PATH=/path/to/libGL.so/
