### ISSUE TITLE
NVIDEA crash - FAST-ICP

### ISSUE THREAD

**Issue by rolarsen** [smistad/FAST#116]
debugger seems to crash at this statement...

https://github.com/smistad/FAST/blob/b27022042c9fa3fdf49f787d1882f1f0e310dc76/source/FAST/Visualization/Renderer.cpp#L170

**Comment by smistad** [comment]
I assume it is actually the line before that is causing the crash? As line 170 can't possibly crash the program.

I can't see any obvious mistakes here, maybe a multi threading GL context issue?
It seems to me that this code doesn't need to be here. Since I am not able to reproduce this error, could you try the following:
Move lines 166-182 to the end of the Renderer::createShaderProgram method (after the for loop).
Try and see if that helps

**Comment by smistad** [comment]
Solved in https://github.com/smistad/FAST/commit/289bdbe27db3212101c7bcbf79e4a041124a5733
