### ISSUE TITLE
getDirectoryList fails on Windows for directories with additional attributes

### ISSUE THREAD

**Issue by rolarsen** [smistad/FAST#129]
https://github.com/smistad/FAST/blob/9d03eb212c4e39685d019ad64dc5f44e83f06209/source/FAST/Utility.cpp#L728

should be  

if(getDirectories && (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY)) {

**Comment by smistad** [comment]
I see.. FILE_ATTRIBUTE_DIRECTORY is a mask. 

But dwFileAttributes may have multiple 1s, so shouldn't the comparison then be either: (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0 or (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) == 16, since FILE_ATTRIBUTE_DIRECTORY has value 16 (hex 0x10). Because the comparison data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY only have two outcomes 0 or 16. 

Perhaps 0 becomes false and 16 becomes true in an if statement in C++? Probably better to be exact in the comparison though

**Comment by rolarsen** [comment]
C++ true equals !=0


-


Roar Larsen

Senior Software Developer



Nisonic AS
Havnegata 7, 7010 Trondheim, Norway
roar@nisonic.com
+47 915 10 203

<http://www.nisonic.com>www.nisonic.com<http://www.nisonic.com>



________________________________
